### PR TITLE
Use pip instead of setup.py

### PR DESCRIPTION
**Pull request by Zeitsperre**

### CODE REVIEW

**Comment by Zeitsperre** [comment]
@tlvu Work for you? ;)

**Comment by tlvu** [comment]
> @tlvu Work for you? ;)

Perfectly :D

**Comment by tlvu** [comment]
Note each time you force push, the PR will track it, see "Zeitsperre force-pushed the use_pip_docker branch from 0cdf250 to 7c363a1 8 minutes ago" so you can technically go back if you screw up as well.

**Comment by Zeitsperre** [comment]
Being able to revert is nice as well. KK, I'll work on these ingrained behaviours in the future.

**Comment by tlvu** [comment]
> Being able to revert is nice as well. KK, I'll work on these ingrained behaviours in the future.

Yeah, leaving trace of "why" you make a change not only save other people that was not in the "initial" review process but can also save your own future self because in french there is a saying "la mémoire est une faculté qui oublie".

**Pull request merged**
