### PR TITLE
Easier to deploy new template to existing project using cruft

### PR DESCRIPTION
**Pull request by tlvu**
## Overview

This PR is part of issue https://github.com/bird-house/cookiecutter-birdhouse/issues/61

Matching Raven cookiecutter update PR https://github.com/Ouranosinc/raven/pull/271

Changes:

* Added `cruft` to environment.  Added `scaraplate` and `cookiecutter_project_upgrader` as well in the history, for reference, before settling down for `cruft`.  Cruft was chosen for its simplicity.  The other 2 tools have more advanced merge conflict resolution but is harder to setup and use and for very diverging project like Raven for example, it's not good enough to be worth the added complexity.

* Other noticeable fixes from merging with Raven, see commits more more:
  * fix wrong `.readthedocs.yml` config file name and updated to version 2
  * add `environment-docs.yml` to avoid bursting memory limit on ReadTheDocs build
  * add repo github link in README
  * use `cookiecutter.project_short_description` for Texinfo output in `docs/source/conf.py`
  * add new config cookiecutter.project_readthedocs_name because Raven docs is https://pavics-raven.readthedocs.io which is different than `https://{{ cookiecutter.project_repo_name }}.readthedocs.io`.  This also fix some inconsistencies that we only sometime replace "_" with "-" and sometime not in the readthedocs name.  Fixed some wrong RtD urls on Raven side.
  * fix wrong httpS used for WPS_URL in Makefile, breaking Travis docs and notebook build

Documentation about how to use `cruft` will be in another PR.  Getting this PR out to complete Raven template refresh.

## Additional Information

Links to other issues or sources.

### CODE REVIEW

**Comment by tlvu** [comment]
Working on merging the Makefile between Raven and the Cookiecutter, why did we remove all the anaconda targets from the Cookiecutter?  

They seem pretty useful to avoid having to remember all the  different steps and commandline options to create the environment.  

If we do not want to force those anaconda targets on users, just remove them as dependencies from other build targets.  If needed, user will simply have to call those anaconda targets explicitly.

**Comment by huard** [comment]
@cehbrecht will have a more complete answer, but I seem to remember it was difficult to maintain consistent behavior across platforms and conda versions.

**Comment by cehbrecht** [comment]
> @cehbrecht will have a more complete answer, but I seem to remember it was difficult to maintain consistent behavior across platforms and conda versions.

@tlvu ... we ware running into issues when using different shells (bash, zsh, ...) ... it felt to complex to solve this in the Makefile. That is why we decided to keep the conda part to the user and just describe it in the documentation.

**Comment by cehbrecht** [comment]
@tlvu maybe add something to the docs how to use `cruft`? A link ... a short example ...

**Comment by cehbrecht** [comment]
@tlvu feel free to merge when ready.

**Comment by tlvu** [comment]
> @tlvu ... we ware running into issues when using different shells (bash, zsh, ...) ... it felt to complex to solve this in the Makefile. That is why we decided to keep the conda part to the user and just describe it in the documentation.

@cehbrecht is it simply because we hardcode bash inside the Makefile?  Maybe a possible simple fix is simply not referencing any shell inside the Makefile and let the current user's shell take precedence.  Who is using zsh so can possibly test this change?

**Comment by tlvu** [comment]
> @tlvu maybe add something to the docs how to use `cruft`? A link ... a short example ...

@cehbrecht will be in next PR.  I'd like to get this PR out because Raven template refresh depends on it and I hate hoarding open PR for a long time.

**Pull request merged**
