### PR TITLE
Issue 77 fix readme links

### LINKED ISSUE #77: doc links not working on github's view of readme
All links such as ``` `file:`Dockerfile` ``` are not working when clicking on them from github's ui view in the README.
This can be fixed by replacing them with references in the .rst (resolves on github side) and providing the root path of the repo to the `conf.py` to preserve resolution during building docs on readthedocs and in shell.
You can check  https://github.com/ouranosinc/magpie 's `README.rst` and `docs/conf.py` files for a working setup with above description.

### PR DESCRIPTION
**Pull request by cehbrecht**
## Overview

This PR fixes #77. It skips the `file:` directive in the readme. Referenced files are part of the template and not the docs.

### CODE REVIEW

**Comment by cehbrecht** [comment]
@fmigneault I have added a link to `.travis.yml` ... but it will only work on github, not in the sphinx docs:
https://github.com/bird-house/cookiecutter-birdhouse/pull/78/commits/5e7e4ccc7765becd8a97c4f35594b132c913c682

**Comment by fmigneault** [comment]
@cehbrecht 
I think you might need to add the root path to the docs' `config.py` (with `sys.insert` or similar).
It should then be able to auto-resolve the relative path `./{{cookiecutter.project_repo_name}}` correctly.

**Comment by cehbrecht** [comment]
> @cehbrecht
> I think you might need to add the root path to the docs' `config.py` (with `sys.insert` or similar).
> It should then be able to auto-resolve the relative path `./{{cookiecutter.project_repo_name}}` correctly.

I tried ... but that alone didn't help. I think `autoapi` would use this ... but within the plugin code.

**Review by huard — APPROVED** [review]

**Comment by Zeitsperre** [comment]
Obsolete due to recent changes to the template.

**Pull request closed without merging**
