### PR TITLE
fix empty autodoc processes list silent docs build failure

### PR DESCRIPTION
**Pull request by tlvu**
Currently, autodoc failure are treated as warnings only, resulting in
empty processes list, see
https://pavics-sdi.readthedocs.io/projects/raven/en/latest/processes.html.

This fix will turn these warnings into build failure on RtD and on
Travis-CI so we can catch those errors earlier.

Right now these warnings are falling silently !

Also changed Travis-CI config so it also builds Epub and Latex format as RtD to catch RtD errors before PR is merged.

Common fixes for those warnings are backported here.

Bonus we also catch nonexisting document reference and missing reference
in toctree, see below sample Raven warnings during docs build.

Raven succesful build logs with warnings on RtD:
https://readthedocs.org/api/v2/build/11487109.txt

/home/docs/checkouts/readthedocs.org/user_builds/pavics-raven/checkouts/latest/docs/source/index.rst:14:
WARNING: toctree contains reference to nonexisting document 'pyraven'
WARNING: autodoc: failed to import process 'processes.RavenProcess' from
module 'raven'; the following exception was raised:
No module named 'xclim.core'
WARNING: autodoc: failed to import process
'processes.RavenGR4JCemaNeigeProcess' from module 'raven'; the following
exception was raised:
No module named 'xclim.core'
WARNING: autodoc: failed to import process
'processes.RavenMOHYSEProcess' from module 'raven'; the following
exception was raised:
No module named 'xclim.core'
WARNING: autodoc: failed to import process 'processes.RavenHMETSProcess'
from module 'raven'; the following exception was raised:
No module named 'xclim.core'
WARNING: autodoc: failed to import process 'processes.RavenHBVECProcess'
from module 'raven'; the following exception was raised:
No module named 'xclim.core'
WARNING: autodoc: failed to import process
'processes.ObjectiveFunctionProcess' from module 'raven'; the following
exception was raised:
No module named 'xclim.core'
looking for now-outdated files... none found
pickling environment... done
checking consistency...
/home/docs/checkouts/readthedocs.org/user_builds/pavics-raven/checkouts/latest/docs/source/notebooks/Region_selection.ipynb:
WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/pavics-raven/checkouts/latest/docs/source/notebooks/Running_models_with_multiple_timeseries_files.ipynb:
WARNING: document isn't included in any toctree

This PR has been tested on Raven PR https://github.com/Ouranosinc/raven/pull/293, Finch PR https://github.com/bird-house/finch/pull/130, FlyingPigeon https://github.com/bird-house/flyingpigeon/pull/337, https://github.com/bird-house/flyingpigeon/pull/336, Emu https://github.com/bird-house/emu/pull/105

### CODE REVIEW

**Comment by cehbrecht** [comment]
Not sure if we would like to have this optional (fail on warning). It might be hard to get the api docs rendered on RTD ...

**Comment by tlvu** [comment]
> Not sure if we would like to have this optional (fail on warning). It might be hard to get the api docs rendered on RTD ...

@cehbrecht Could you elaborate on the problem?  I'll put a comment next to that option so downstream project can choose to disable it.  But I'd rather have it turn on by default to avoid silent failure unless you tell me it's a very frequent problem and this option will just make our life much harder than the advantage it brings.

**Comment by cehbrecht** [comment]
> > Not sure if we would like to have this optional (fail on warning). It might be hard to get the api docs rendered on RTD ...
> 
> @cehbrecht Could you elaborate on the problem? I'll put a comment next to that option so downstream project can choose to disable it. But I'd rather have it turn on by default to avoid silent failure unless you tell me it's a very frequent problem and this option will just make our life much harder than the advantage it brings.

@tlvu I'm always happy when build on RTD works ... it is sometimes troublesome due to the dependencies. Feel free to merge ... we can adapt in the projects.

**Comment by tlvu** [comment]
> I'm always happy when build on RTD works ... it is sometimes troublesome due to the dependencies. Feel free to merge ... we can adapt in the projects.

Thanks @cehbrecht.  I'll merge this PR once I deploy this change to Raven and confirm it works.  Maybe I'll hit the problem you mentioned and will reconsider.  Will for sure add a comment to the RtD option so other projects feel comfortable disabling it if they need.

**Comment by cehbrecht** [comment]
> > I'm always happy when build on RTD works ... it is sometimes troublesome due to the dependencies. Feel free to merge ... we can adapt in the projects.
> 
> Thanks @cehbrecht. I'll merge this PR once I deploy this change to Raven and confirm it works. Maybe I'll hit the problem you mentioned and will reconsider. Will for sure add a comment to the RtD option so other projects feel comfortable disabling it if they need.

@tlvu ok. Thanks :)

**Comment by tlvu** [comment]
@cehbrecht @Zeitsperre 
Update: I've tested this PR on Raven (PR https://github.com/Ouranosinc/raven/pull/293) and removing all the RtD build warnings was not as simple as I expected but I got it finally (relevant changes backported here).

To further reduce RtD build to fail after PR is merged, I've also modified Travis-CI to also build Epub and Latex format (to do the same thing as RtD) so Travis-CI can also catch RtD errors.

**Pull request merged**
