### PR TITLE
Upstream changes

### PR DESCRIPTION
**Pull request by Zeitsperre**
## Overview

Changes:

* Merged upstream master branch
* Includes the "modernization" changes

### CODE REVIEW

**Review by cehbrecht — APPROVED** [review]

**Comment by cehbrecht** [comment]
@Zeitsperre thanks :) Looks good to me. 

we will probably move to pygeoapi (ogcapi-processes) and skip pywps in the future. Probably we want to keep a cookiecutter for setting up new projects (birds). It is then also a chance to build an improved version ... for example using markdown for documentation?

**Comment by Zeitsperre** [comment]
@cehbrecht 

I think Markdown makes sense for some of the documentation, mostly the top-level files (`README`, `CHANGELOG`, `SECURITY`, etc.), but given that we use `numpy` docstrings everywhere, ReStructuredText makes for consistent docs when rendered.

Would you want to make a separate cookiecutter for the PyGeoAPI-based projects? Start completely from scratch (or port from here/upstream?). There are a lot of patterns I held back on here to not cause headaches in existing projects, but I imagine a new template could benefit from them.

In any case, thanks for the review. Will update a few existing projects with this.

**Comment by Zeitsperre** [comment]
@cehbrecht

There are so many changes since 2020 that I'm setting this package as `v1.0.0` of the package. We could technically place this on PyPI, but there would be no point, IMO. Perhaps a better idea would be to publish this on Zenodo for future reference.

I'll merge this now, but let me know in the day if that's of interest to you.

**Comment by cehbrecht** [comment]
> @cehbrecht
> 
> I think Markdown makes sense for some of the documentation, mostly the top-level files (`README`, `CHANGELOG`, `SECURITY`, etc.), but given that we use `numpy` docstrings everywhere, ReStructuredText makes for consistent docs when rendered.
> 
> Would you want to make a separate cookiecutter for the PyGeoAPI-based projects? Start completely from scratch (or port from here/upstream?). There are a lot of patterns I held back on here to not cause headaches in existing projects, but I imagine a new template could benefit from them.
> 
> In any case, thanks for the review. Will update a few existing projects with this.

I would prefer to start with new projects (and a new cookiecutter) for pygeoapi. To avoid some headaches :)

**Comment by cehbrecht** [comment]
> @cehbrecht
> 
> There are so many changes since 2020 that I'm setting this package as `v1.0.0` of the package. We could technically place this on PyPI, but there would be no point, IMO. Perhaps a better idea would be to publish this on Zenodo for future reference.
> 
> I'll merge this now, but let me know in the day if that's of interest to you.

I'm fine with version v1.0.0 ... finally :) Personally I don't need a Zenodo reference.

**Pull request merged**
